name: calendar
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  table_calendar: ^3.0.9
  carousel_slider: 4.2.1
  flutter_riverpod: ^2.4.5
  freezed_annotation: ^2.4.1
  freezed: ^2.4.5
  riverpod_annotation: ^2.3.0
  riverpod_generator: ^2.3.5
  flutter_datetime_picker: ^1.5.1
  flutter_datetime_picker_plus: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true



